BATCH_SIZE = 8
BUFFER_SIZE = 10000
EPOCHS = 5
STEP = 1
HISTORY_SIZE = 4
TARGET_DIS = 1
FEATURES = ['Close', 'Volume', 'MA_short', 'Change_1', 'Change_4', 'Change_8']
DATA_DIR = 'data/SPY.csv'
DATA_SYM = 'SPY'
